### ISSUE TITLE
Add `requirements.txt` for python detectors

### ISSUE THREAD

**Issue by jasmeet0915** [atom-robotics-lab/ros-perception-pipeline#20]
Add a `requirements.txt` file in the `object_detection` package for all the required dependencies for the python based detectors (YOLOv5, YOLOv8, RetinaNet and EfficientDet).

Also, update the installation instructions in `README.md` to use pip to install python dependencies from the `requirements.txt` file

**Comment by topguns837** [comment]
Hey @Wolfmyths , Thanks for your effort and valuable time. We would love you to look around, play with this project and be an active contributor in the coming future.

Cheers
