### ISSUE TITLE
Imports not working when using virtual environment

### ISSUE THREAD

**Issue by jasmeet0915** [atom-robotics-lab/ros-perception-pipeline#22]
When using a virtual environment, the imports are not working. Not sure about the reason but ROS 2 isn't adding the virtual environment  site-packages path to `PYTHONPATH`. 

A simple solution would be to manually export `PYTHONPATH` if you are using a virtual environment. I guess this can be added as a note in the README.

**Comment by topguns837** [comment]
Resolved in #25
