### ISSUE TITLE
Add a ROS 2 Param to enable publishing of output image from the object detection node

### ISSUE THREAD

**Issue by jasmeet0915** [atom-robotics-lab/ros-perception-pipeline#28]
Add a ROS 2 Param like `publish_output_img` to enable the publishing of output images with the bounding boxes. This would allow configuring and opting out of continuous image publishing to save computation and bandwidth

**Comment by topguns837** [comment]
Resolved in https://github.com/atom-robotics-lab/ros-perception-pipeline/pull/25
